AllCops:
  require: rubocop-rails

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false